---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Turtle Project 2023

<!-- badges: start -->
<!-- badges: end -->

This repo contains miscellaneous reports in quarto (`.qmd`), Rmarkdown (`.Rmd`). The aim is to use this repo when we need to collaborate on reports, especially ones that include both text and code.

## Adding reports

Create __separate subfolders__ for each project and put all necessary assets there, such as shared data sets, scripts, quarto documents and other necessary files. Name subfolders in a descriptive way, preferrably prefixed with creation year (i.e. "2023_project_name").

> NB: Do not add indvidual files larger than 50 Mb here, please ([why not?](https://rtyley.github.io/bfg-repo-cleaner/)). Larger assets can be instead be added as GitHub Releases if required and can then be accessed from within a report using [`piggyback`](https://github.com/ropensci/piggyback)!
Specific functions attached to projects can be included as well, but ideally most reusable 
functions should be placed in other repos (`bibliotools`, `bibliomatrix` etc) and this repo should 
mainly contain text and code related to specific analyses and reports. 
