name: Docker image of Quarto script

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/turtle-image:${{ github.sha }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/turtle-image:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/turtle-image:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/turtle-image:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/turtle-image:latest
